# Generated by Django 5.1 on 2025-11-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_agentprofileproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
