# Generated by Django 5.1 on 2025-11-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
