# Generated by Django 5.1 on 2025-12-11 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_message_hidden_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
