# Generated by Django 5.1.14 on 2025-12-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
