# Generated by Django 5.1.14 on 2025-12-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_message_deleted_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
