# Generated by Django 5.1.14 on 2025-12-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conv_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='msg_conv_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='msg_read_at_idx',
        ),
    ]
