"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv()  # take environment variables from .env.

# Observability / Error tracking
'''SENTRY_DSN = os.getenv('SENTRY_DSN')
if SENTRY_DSN:
    # sentry_sdk.init(
    #     dsn=SENTRY_DSN,
    #     integrations=[DjangoIntegration()],
    #     traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE')),
    #     profiles_sample_rate=float(os.getenv('SENTRY_PROFILES_SAMPLE_RATE')),
    #     send_default_pii=os.getenv('SENTRY_SEND_DEFAULT_PII').lower() in ('1', 'true', 'yes'),
    # )
'''
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment; REQUIRED in production, fallback only for development.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('DJANGO_ENV') == 'production':
        raise ValueError(
            "SECRET_KEY environment variable is required in production. "
            "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
        )

# DEBUG should be False in production. Control via environment variable.
DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# 1. Get the string of hosts from your environment (which came from .env)
HOSTS_STRING = os.environ.get('ALLOWED_HOSTS', '') 

# 2. Split the string by commas to create the required Python list
ALLOWED_HOSTS = HOSTS_STRING.split(',') if HOSTS_STRING else []

# Validate production settings
if os.getenv('DJANGO_ENV') == 'production':
    if DEBUG:
        raise ValueError("DEBUG must be False in production. Set DEBUG=False in environment.")
    if not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS:
        raise ValueError("ALLOWED_HOSTS must be explicitly set in production and not contain '*'.")
    if not os.getenv('CSRF_TRUSTED_ORIGINS'):
        raise ValueError("CSRF_TRUSTED_ORIGINS must be explicitly set in production.")
    if not os.getenv('CORS_ALLOWED_ORIGINS'):
        raise ValueError("CORS_ALLOWED_ORIGINS must be explicitly set in production.")

# Security-sensitive settings that should be set for production.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', str(not DEBUG)).lower() in ('true', '1', 'yes')
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 0)) if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', str(not DEBUG)).lower() in ('true', '1', 'yes')
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', str(not DEBUG)).lower() in ('true', '1', 'yes')

# Additional security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Proxy SSL header for HTTPS behind reverse proxy (e.g., nginx, load balancer)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie settings
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = False



# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_filters',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.microsoft',
    'anymail',
    'storages',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'channels',

    # Local apps
    'accounts',
    'properties',
    'communications',
    'insights',
    'features',
]

SITE_ID = 1

# Django-allauth configuration
ACCOUNT_AUTHENTICATION_METHOD = os.getenv('ACCOUNT_AUTHENTICATION_METHOD', 'email')
ACCOUNT_EMAIL_REQUIRED = os.getenv('ACCOUNT_EMAIL_REQUIRED', 'True').lower() in ('true', '1', 'yes')
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False # Users will log in with email
ACCOUNT_EMAIL_VERIFICATION = os.getenv('ACCOUNT_EMAIL_VERIFICATION', 'mandatory')
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_VERIFICATION = os.getenv('SOCIALACCOUNT_EMAIL_VERIFICATION', 'optional')

# Redirect after login (you can change this to your frontend URL)
LOGIN_REDIRECT_URL = os.getenv('LOGIN_REDIRECT_URL', '/')

# Social provider placeholders.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.getenv('SOCIAL_GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('SOCIAL_GOOGLE_SECRET', ''),
            'key': ''
        }
    },
    'facebook': {
        'SCOPE': ['email'],
        'APP': {
            'client_id': os.getenv('SOCIAL_FACEBOOK_CLIENT_ID', ''),
            'secret': os.getenv('SOCIAL_FACEBOOK_SECRET', ''),
            'key': ''
        }
    },
    'microsoft': {
        'SCOPE': ['User.Read'],
        'APP': {
            'client_id': os.getenv('SOCIAL_MICROSOFT_CLIENT_ID', ''),
            'secret': os.getenv('SOCIAL_MICROSOFT_SECRET', ''),
            'key': ''
        }
    },
    'apple': {
        'APP': {
            'client_id': os.getenv('SOCIAL_APPLE_CLIENT_ID', ''),
            'secret': os.getenv('SOCIAL_APPLE_SECRET', ''),
            'key': ''
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] if not DEBUG else [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # SessionAuth is useful for the browsable API and admin site.
        # Keep it for development, consider removing for a stateless production API.
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# CSRF trusted origins - MUST be set in production
csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS')
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()]
elif not DEBUG:
    CSRF_TRUSTED_ORIGINS = [] # Empty list is a safe default if not debug
else:
    # Default development origins if not set
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000', 'http://127.0.0.1:3000',
        'http://localhost:5173', 'http://127.0.0.1:5173',
    ]

# CORS allowed origins - MUST be set in production
cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS')
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',') if origin.strip()]
elif not DEBUG:
    CORS_ALLOWED_ORIGINS = [] # Empty list is a safe default if not debug
else:
    # Default development origins
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000', 'http://127.0.0.1:3000',
        'http://localhost:5173', 'http://127.0.0.1:5173',
        'http://localhost:8000', 'http://127.0.0.1:8000',
    ]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT')
CORS_ALLOW_HEADERS = ('accept', 'authorization', 'content-type', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with')

GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')
GOOGLE_MAPS_GEOCODE_TIMEOUT = int(os.getenv('GOOGLE_MAPS_GEOCODE_TIMEOUT', 5))
REDIS_URL = os.getenv('REDIS_URL')

# M-Pesa Payment Integration (Daraja API)
DAR_AFFILIATE_CONSUMER_KEY = os.getenv('DAR_AFFILIATE_CONSUMER_KEY')
DAR_AFFILIATE_CONSUMER_SECRET = os.getenv('DAR_AFFILIATE_CONSUMER_SECRET')
DAR_SHORTCODE = os.getenv('DAR_SHORTCODE')
DAR_PASSKEY = os.getenv('DAR_PASSKEY')
MPESA_API_BASE = os.getenv('MPESA_API_BASE', 'https://sandbox.safaricom.co.ke')
MPESA_CALLBACK_URL = os.getenv('MPESA_CALLBACK_URL')

# Twilio SMS Integration
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')

# Stripe Payment Integration
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# Frontend URL used in activation emails and links
FRONTEND_URL = os.getenv('FRONTEND_URL')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'


# Database
# Use PostgreSQL in production. Use dj-database-url to parse DATABASE_URL env var.
import dj_database_url

if os.getenv('DATABASE_URL'):
    DATABASES = {'default': dj_database_url.config(conn_max_age=600, ssl_require=os.getenv('DB_SSL_REQUIRE', 'true').lower() in ('true', '1', 'yes'))}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Cache configuration
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True, # Don't crash if Redis is down
            }
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'property-cache',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 9}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": os.getenv("JWT_AUDIENCE", "smartdalali:web"),
    "ISSUER": os.getenv("JWT_ISSUER", "smartdalali"),
    "LEEWAY": int(os.getenv("JWT_LEEWAY_SECONDS", 5)),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_OBTAIN_SERIALIZER": "accounts.serializers.MyTokenObtainPairSerializer",
}

# Channels
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}}


# Internationalization
LANGUAGE_CODE = 'en'
LANGUAGES = [('en', 'English'), ('sw', 'Kiswahili')]
LOCALE_PATHS = [BASE_DIR / 'locale']
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static_root"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
if AWS_STORAGE_BUCKET_NAME:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN')
    AWS_QUERYSTRING_AUTH = False # URLs should be public
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/" if AWS_S3_CUSTOM_DOMAIN else f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / "media_root"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

# Transactional email providers (e.g., SendGrid)
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
if SENDGRID_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.sendgrid.EmailBackend'
    ANYMAIL = {'SENDGRID_API_KEY': SENDGRID_API_KEY}

LOGOUT_REDIRECT_URL = '/'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}

# drf-spectacular (API Schema) settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'SmartDalali API',
    'DESCRIPTION': 'API for property listings, user management, and more.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Firebase Admin SDK Configuration
import firebase_admin
from firebase_admin import credentials
import json

FIREBASE_CREDENTIALS_JSON = os.getenv('FIREBASE_CREDENTIALS_JSON')

# Initialize Firebase Admin SDK if not already initialized
if not firebase_admin._apps:
    if FIREBASE_CREDENTIALS_JSON:
        try:
            # Parse the JSON string into a dictionary
            firebase_creds_dict = json.loads(FIREBASE_CREDENTIALS_JSON)
            cred = credentials.Certificate(firebase_creds_dict)
            firebase_admin.initialize__app(cred)
        except (json.JSONDecodeError, ValueError) as e:
            error_message = f"Firebase credentials JSON is malformed: {e}"
            if os.getenv('DJANGO_ENV') == 'production':
                raise ValueError(error_message)
            else:
                print(f"Warning: {error_message}")
        except Exception as e:
            error_message = f"Could not initialize Firebase Admin SDK: {e}"
            if os.getenv('DJANGO_ENV') == 'production':
                raise ValueError(error_message)
            else:
                print(f"Warning: {error_message}")
    elif os.getenv('DJANGO_ENV') == 'production':
        # In production, require Firebase credentials
        raise ValueError("FIREBASE_CREDENTIALS_JSON environment variable is not set. This is required for production.")
    else:
        # In development, it's a non-fatal warning
        print("Warning: FIREBASE_CREDENTIALS_JSON is not set. Firebase authentication will not work.")

# AI Configuration
AI_API_KEY = os.getenv('AI_API_KEY')
