# Generated by Django 5.1.14 on 2025-12-02 11:54

import properties.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaproperty',
            name='Images',
            field=models.ImageField(null=True, upload_to='property_images/', validators=[properties.validators.FileTypeValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif'])]),
        ),
        migrations.AlterField(
            model_name='mediaproperty',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='property_videos', validators=[properties.validators.FileTypeValidator(allowed_mimetypes=['video/mp4', 'video/quicktime', 'video/x-msvideo', 'video/webm'])]),
        ),
    ]
