# Generated by Django 5.1.14 on 2025-12-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_mediaproperty_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvisit',
            options={'ordering': ['-created_at']},
        ),
    ]
