# Generated by Django 5.1 on 2025-12-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyvisit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent')], db_index=True, default='for_rent', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Land', 'Land'), ('Villa', 'Villa'), ('Shop', 'Shop'), ('Warehouse', 'Warehouse')], db_index=True, max_length=20),
        ),
    ]
