# Generated by Django 5.1.14 on 2025-12-12 04:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_listing_type_alter_property_bathrooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvisit',
            options={},
        ),
        migrations.RemoveField(
            model_name='propertyvisit',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='propertyvisit',
            name='visitor',
        ),
        migrations.AddField(
            model_name='propertyvisit',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits_scheduled', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvisit',
            name='date',
            field=models.DateField(default=datetime.date(2025, 12, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvisit',
            name='time',
            field=models.TimeField(default=datetime.time(3, 58, 36, 134274)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvisit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits_requested', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyvisit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
