# Generated by Django 5.1 on 2025-12-12 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertyvisit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_contact_attempts', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('last_engagement', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLeadMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('new_messages', models.PositiveIntegerField(default=0)),
                ('conversations_started', models.PositiveIntegerField(default=0)),
                ('response_time_minutes', models.PositiveIntegerField(default=0, help_text='Average response time in minutes')),
                ('total_responses', models.PositiveIntegerField(default=0, help_text='Number of responses sent this day')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['agent', '-date'], name='properties__agent_i_fa2182_idx')],
                'unique_together': {('agent', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GeographicInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_index=True, max_length=100)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Agent whose properties are being viewed (null for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geographic_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-view_count'],
                'indexes': [models.Index(fields=['agent', '-date'], name='properties__agent_i_6bac3b_idx'), models.Index(fields=['location_name', '-date'], name='properties__locatio_4fd73e_idx')],
                'unique_together': {('location_name', 'agent', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PropertyViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='properties.property')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_view_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['property', '-viewed_at'], name='properties__propert_1518cd_idx'), models.Index(fields=['viewer', '-viewed_at'], name='properties__viewer__0ee0eb_idx'), models.Index(fields=['device_type'], name='properties__device__b579b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyEngagementPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(db_index=True)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('activity_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=10)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_inquiries', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_start_date', 'day_of_week'],
                'indexes': [models.Index(fields=['agent', '-week_start_date'], name='properties__agent_i_e70c6a_idx')],
                'unique_together': {('agent', 'week_start_date', 'day_of_week')},
            },
        ),
    ]
