# Generated by Django 5.1 on 2025-11-23 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_feature_subscriptionplan_agentprofile_current_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars')),
                ('review', models.TextField(blank=True, help_text='Optional review text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='The agent being rated', on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='Property this rating is related to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_ratings', to='properties.property')),
                ('user', models.ForeignKey(help_text='The user giving the rating', on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('agent', 'user')},
            },
        ),
    ]
