# Generated by Django 5.1 on 2025-11-24 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_propertyfeature_delete_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaproperty',
            name='caption',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaproperty',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='property_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])]),
        ),
    ]
