# Generated by Django 5.1 on 2025-11-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_propertyvisit_options_propertyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When property was archived', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='auto_archive_days',
            field=models.IntegerField(default=7, help_text='Days before auto-archiving sold/rented properties'),
        ),
    ]
