# Generated by Django 5.1 on 2025-11-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_archived_at_property_auto_archive_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='properties.subscriptionplan')),
            ],
            options={
                'unique_together': {('plan', 'feature')},
            },
        ),
    ]
