# Generated by Django 5.1 on 2025-11-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_planfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.AlterUniqueTogether(
            name='planfeature',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='PlanFeature',
        ),
    ]
