# Generated by Django 5.1 on 2025-11-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_subscriptionplan'),
        ('properties', '0013_remove_planfeature_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='features.subscriptionplan'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
