# Generated by Django 5.1 on 2025-11-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description_sw',
            field=models.TextField(blank=True, help_text='Swahili description', null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_sw',
            field=models.CharField(blank=True, help_text='Swahili name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_sw',
            field=models.TextField(blank=True, help_text='Swahili description', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_sw',
            field=models.CharField(blank=True, help_text='Swahili name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If true, available to all users regardless of plan'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
